### ISSUE TITLE
严重bug

### ISSUE THREAD

**Issue by cgddgc** [lanyi1998/DNSlog-GO#13]
有个很严重的bug，只有在页面上复制的子域名才有结果，当要自定义域名的时候，比如说要执行命令（`whoami`.xxx.xxx）、外带数据的时候就用不了了

**Comment by lanyi1998** [comment]
![image](https://user-images.githubusercontent.com/31091395/148766030-23642a80-f94e-4f78-a5e6-fdfc174d9fde.png)

不存在此问题
