### ISSUE TITLE
DNSLOG最新版本问题

### ISSUE THREAD

**Issue by longzaizai001** [lanyi1998/DNSlog-GO#16]
发布时间2022 年 1 月 2 日 
在Windows系统启动程序时，读取不了配置文件中的domain文段，一直是默认的demo.com

**Comment by lanyi1998** [comment]
是否清空浏览器localStorage

**Comment by longzaizai001** [comment]
ok 浏览器localStorage没有设置  重新设置了一次 可以了 感谢大佬
