### ISSUE TITLE
Linux环境下，配置文件不应该是config.ini的吧

### ISSUE THREAD

**Issue by zxhubo** [lanyi1998/DNSlog-GO#17]
Hi，

  如果要在Linux 环境下部署，那么配置文件就不应该是config.ini的吧。

**Comment by lanyi1998** [comment]
都是config.ini


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: zxhubo ***@***.***&gt;
发送时间: 2022年4月1日 11:37
收件人: lanyi1998/DNSlog-GO ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[lanyi1998/DNSlog-GO] Linux环境下，配置文件不应该是config.ini的吧 (Issue #17)





 
Hi，
 
如果要在Linux 环境下部署，那么配置文件就不应该是config.ini的吧。

**Comment by zxhubo** [comment]
@lanyi1998 谢谢老哥的解释都哈。
