### ISSUE TITLE
cannot resolve 3jehr.log.xxx.online: Unknown host

### ISSUE THREAD

**Issue by ybdt** [lanyi1998/DNSlog-GO#22]
ping log.xxx.online可以解析，ping 3jehr.log.xxx.online则提示未知主机

另外，readme中dns方面的配置，太粗略了，而且有点乱，初次配置的人看的很迷糊。。

**Comment by ybdt** [comment]
参照其他教程解决了

**Comment by dead5nd** [comment]
如何解决的呢，我也遇到了这个问题
