### ISSUE TITLE
搭建完成后，ping域名提示找不到主机

### ISSUE THREAD

**Issue by FishM4n** [lanyi1998/DNSlog-GO#5]
提示Unknown host
![image](https://user-images.githubusercontent.com/59049655/113706886-c0cf9580-9711-11eb-8b14-ff66070f6200.png)

**Comment by FishM4n** [comment]
解决

**Comment by invidiguaJq** [comment]
> 解决

老哥，咋解决的啊

**Comment by lanyi1998** [comment]
换国外vps


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: invidiguaJq ***@***.***&gt;
发送时间: 2021年12月21日 23:43
收件人: lanyi1998/DNSlog-GO ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[lanyi1998/DNSlog-GO] 搭建完成后，ping域名提示找不到主机 (#5)





  
解决
  
老哥，咋解决的啊
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
