### ISSUE TITLE
服务器启动53端口时卡住

### ISSUE THREAD

**Issue by Pear1y** [lanyi1998/DNSlog-GO#7]
在 Ubuntu 上装了个 Server端，修改配置文件后启动主程序提示 53端口已占用，遂 `systemctl stop systemd-resolved` 关闭，再启动主程序卡在 `DNS Listing Start...`
在此期间，NS记录修改未满 24h，未生效。
所以主程序启动卡住是因为查询不到NS记录么？

**Comment by lanyi1998** [comment]
不是，DNS Listing Star是已经启动成功了
