### ISSUE TITLE
能按照当前登陆人所选的子域名加载对应数据嘛？

### ISSUE THREAD

**Issue by Coderzgh** [lanyi1998/DNSlog-GO#8]
能按照当前登陆人所选的子域名加载对应数据嘛？现在是所有人上来 都能加载所有历史数据 ，谢谢 @lanyi1998

**Comment by 6f3Ng** [comment]
``` html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>DNSLog</title>
    <meta name="keywords" content="dnslog"/>
    <meta name="description" content="dnslog"/>
    <script src="vue.js"></script>
    <!--    <script src="https://cn.vuejs.org/js/vue.js"></script>-->
    <script src="axios.min.js"></script>
</head>
<body>
<div id=header style="text-align:center">
    <hr style=" height:2px;border:none;border-top:2px dashed #87CEFA;"/>
    <br>
</div>
<div style="text-align:center;" id="app">
    <button type="button" v-on:click="GetDomain">刷新记录</button>
    <button type="button" v-on:click="GenPayload">复制随机子域名</button>
    <button type="button" v-on:click="Clean">清空</button>
    <br><br>
    <div id="myDomain">&nbsp;</div>
    <br>
    <center>
        <table id="myRecords" width=700 border="0" cellpadding="5" cellspacing="1" bgcolor="#EFF3FF"
               style="word-break:break-all; word-wrap:break-all;">
            <tr bgcolor="#ADD3EF">
                <th width="50%">DNS Query Record</th>
                <th width="25%">IP Address</th>
                <th width="25%">Created Time</th>
            </tr>
            <td v-if="DnsData == ''" colspan="3" align="center">No Data</td>
            <tr v-for="item in DnsData" v-if="('.'+item.Subdomain).substring(('.'+item.Subdomain).length - document.getElementById('myDomain').innerHTML.length - 1) == '.' + document.getElementById('myDomain').innerHTML">
                <td>{{ item.Subdomain }}</td>
                <td>{{ item.Ipaddress }}</td>
                <td>{{ item.Time }}</td>
            </tr>
        </table>
    </center>
</div>
</body>
<br>
<br>
<br>
<br>
<br>
<br>
<div id=footer>
    <hr style=" height:2px;border:none;border-top:2px dashed #87CEFA;"/>
    <br>
    <center><span style="color:#ADD3EF">DNSLog</span></center>
</div>
<script>
    function formatTimeToStr(date) {
        date = date * 1000
        date = new Date(date)
        var fmt = "mm-dd HH:MM:SS"
        let ret;
        const opt = {
            "Y+": date.getFullYear().toString(),        // 年
            "m+": (date.getMonth() + 1).toString(),     // 月
            "d+": date.getDate().toString(),            // 日
            "H+": date.getHours().toString(),           // 时
            "M+": date.getMinutes().toString(),         // 分
            "S+": date.getSeconds().toString()          // 秒
            // 有其他格式化字符需求可以继续添加，必须转化成字符串
        };
        for (let k in opt) {
            ret = new RegExp("(" + k + ")").exec(fmt);
            if (ret) {
                fmt = fmt.replace(ret[1], (ret[1].length == 1) ? (opt[k]) : (opt[k].padStart(ret[1].length, "0")))
            }
            ;
        }
        ;
        return fmt;
    }
</script>
<script>
    var app = new Vue({
        el: '#app',
        data: {
            DnsData: "",
            Token: "",
            domain: "",
        },
        methods: {
            GetDomain: function () {
                axios.get("/api/getDnsData", {
                    headers: {
                        'token': this.Token
                    }
                }).then(
                    res => {
                        if (res['data']['HTTPStatusCode'] == 200) {
                            if (res['data']['Msg'] != 'null') {
                                this.DnsData = JSON.parse(res['data']['Msg']).reverse();
                                for (var i = 0; i < this.DnsData.length; i++) {
                                    this.DnsData[i].Time = formatTimeToStr(this.DnsData[i].Time)
                                }
                            } else {
                                this.DnsData = "";
                            }
                        }
                        if (res['data']['HTTPStatusCode'] == 403) {
                            alert("token错误");
                            localStorage.clear();
                            location.reload();
                        }
                    }
                )
            },
            Clean: function () {
                axios.get("/api/Clean", {
                    headers: {
                        'token': this.Token
                    }
                }).then()
                this.DnsData = ""
            },
            GenPayload: function () {
                const chars = 'abcdefhijkmnprstwxyz1234567890';
                let randStr = "";
                for (i = 0; i < 5; i++) {
                    randStr += chars.charAt(Math.floor(Math.random() * chars.length));
                }
                let randDomain = randStr + "." + this.domain;
                document.getElementById("myDomain").innerHTML = randDomain;
                var domUrl = document.createElement("input");
                domUrl.value = randDomain;
                domUrl.id = "creatDom";
                document.body.appendChild(domUrl);
                domUrl.select(); // 选择对象
                document.execCommand("Copy"); // 执行浏览器复制命令
                let creatDom = document.getElementById("creatDom");
                creatDom.parentNode.removeChild(creatDom);
                alert("复制成功");
            }
        },
        mounted() {
            let token;
            if (localStorage.getItem("token") == null) {
                token = prompt("请输入Token")
                let data = {"token": token};
                axios.post("/api/verifyToken", data)
                    .then(res => {
                        if (res.data.HTTPStatusCode == "200") {
                            this.Token = token
                            localStorage.setItem("token", token);
                            this.domain = res.data.Msg
                            localStorage.setItem("domain", res.data.Msg);
                        } else {
                            alert("token错误")
                            location.reload()
                        }
                    })
            } else {
                this.Token = localStorage.getItem("token")
                this.domain = localStorage.getItem("domain")
            }
        },
    });
    setInterval("app.GetDomain()", 3000);
</script>

</html>
``` 
我修改了index.html前端界面展示，在前端做了筛选，勉强满足需求了。

**Comment by lanyi1998** [comment]
最近这个需求提的人，很多最近更新


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: 6f3Ng ***@***.***&gt;
发送时间: 2021年12月30日 18:13
收件人: lanyi1998/DNSlog-GO ***@***.***&gt;
抄送: lanyi ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[lanyi1998/DNSlog-GO] 能按照当前登陆人所选的子域名加载对应数据嘛？ (Issue #8)





 <!DOCTYPE html&gt; <html&gt; <head&gt;     <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/&gt;     <title&gt;DNSLog</title&gt;     <meta name="keywords" content="dnslog"/&gt;     <meta name="description" content="dnslog"/&gt;     <script src="vue.js"&gt;</script&gt;     <!--    <script src="https://cn.vuejs.org/js/vue.js"&gt;</script&gt;--&gt;     <script src="axios.min.js"&gt;</script&gt; </head&gt; <body&gt; <div id=header style="text-align:center"&gt;     <hr style=" height:2px;border:none;border-top:2px dashed #87CEFA;"/&gt;     <br&gt; </div&gt; <div style="text-align:center;" id="app"&gt;     <button type="button" v-on:click="GetDomain"&gt;刷新记录</button&gt;     <button type="button" v-on:click="GenPayload"&gt;复制随机子域名</button&gt;     <button type="button" v-on:click="Clean"&gt;清空</button&gt;     <br&gt;<br&gt;     <div id="myDomain"&gt;&amp;nbsp;</div&gt;     <br&gt;     <center&gt;         <table id="myRecords" width=700 border="0" cellpadding="5" cellspacing="1" bgcolor="#EFF3FF"                style="word-break:break-all; word-wrap:break-all;"&gt;             <tr bgcolor="#ADD3EF"&gt;                 <th width="50%"&gt;DNS Query Record</th&gt;                 <th width="25%"&gt;IP Address</th&gt;                 <th width="25%"&gt;Created Time</th&gt;             </tr&gt;             <td v-if="DnsData == ''" colspan="3" align="center"&gt;No Data</td&gt;             <tr v-for="item in DnsData" v-if="('.'+item.Subdomain).substring(('.'+item.Subdomain).length - document.getElementById('myDomain').innerHTML.length - 1) == '.' + document.getElementById('myDomain').innerHTML"&gt;                 <td&gt;{{ item.Subdomain }}</td&gt;                 <td&gt;{{ item.Ipaddress }}</td&gt;                 <td&gt;{{ item.Time }}</td&gt;             </tr&gt;         </table&gt;     </center&gt; </div&gt; </body&gt; <br&gt; <br&gt; <br&gt; <br&gt; <br&gt; <br&gt; <div id=footer&gt;     <hr style=" height:2px;border:none;border-top:2px dashed #87CEFA;"/&gt;     <br&gt;     <center&gt;<span style="color:#ADD3EF"&gt;DNSLog</span&gt;</center&gt; </div&gt; <script&gt;     function formatTimeToStr(date) {         date = date * 1000         date = new Date(date)         var fmt = "mm-dd HH:MM:SS"         let ret;         const opt = {             "Y+": date.getFullYear().toString(),        // 年             "m+": (date.getMonth() + 1).toString(),     // 月             "d+": date.getDate().toString(),            // 日             "H+": date.getHours().toString(),           // 时             "M+": date.getMinutes().toString(),         // 分             "S+": date.getSeconds().toString()          // 秒             // 有其他格式化字符需求可以继续添加，必须转化成字符串         };         for (let k in opt) {             ret = new RegExp("(" + k + ")").exec(fmt);             if (ret) {                 fmt = fmt.replace(ret[1], (ret[1].length == 1) ? (opt[k]) : (opt[k].padStart(ret[1].length, "0")))             }             ;         }         ;         return fmt;     } </script&gt; <script&gt;     var app = new Vue({         el: '#app',         data: {             DnsData: "",             Token: "",             domain: "",         },         methods: {             GetDomain: function () {                 axios.get("/api/getDnsData", {                     headers: {                         'token': this.Token                     }                 }).then(                     res =&gt; {                         if (res['data']['HTTPStatusCode'] == 200) {                             if (res['data']['Msg'] != 'null') {                                 this.DnsData = JSON.parse(res['data']['Msg']).reverse();                                 for (var i = 0; i < this.DnsData.length; i++) {                                     this.DnsData[i].Time = formatTimeToStr(this.DnsData[i].Time)                                 }                             } else {                                 this.DnsData = "";                             }                         }                         if (res['data']['HTTPStatusCode'] == 403) {                             alert("token错误");                             localStorage.clear();                             location.reload();                         }                     }                 )             },             Clean: function () {                 axios.get("/api/Clean", {                     headers: {                         'token': this.Token                     }                 }).then()                 this.DnsData = ""             },             GenPayload: function () {                 const chars = 'abcdefhijkmnprstwxyz1234567890';                 let randStr = "";                 for (i = 0; i < 5; i++) {                     randStr += chars.charAt(Math.floor(Math.random() * chars.length));                 }                 let randDomain = randStr + "." + this.domain;                 document.getElementById("myDomain").innerHTML = randDomain;                 var domUrl = document.createElement("input");                 domUrl.value = randDomain;                 domUrl.id = "creatDom";                 document.body.appendChild(domUrl);                 domUrl.select(); // 选择对象                 document.execCommand("Copy"); // 执行浏览器复制命令                 let creatDom = document.getElementById("creatDom");                 creatDom.parentNode.removeChild(creatDom);                 alert("复制成功");             }         },         mounted() {             let token;             if (localStorage.getItem("token") == null) {                 token = prompt("请输入Token")                 let data = {"token": token};                 axios.post("/api/verifyToken", data)                     .then(res =&gt; {                         if (res.data.HTTPStatusCode == "200") {                             this.Token = token                             localStorage.setItem("token", token);                             this.domain = res.data.Msg                             localStorage.setItem("domain", res.data.Msg);                         } else {                             alert("token错误")                             location.reload()                         }                     })             } else {                 this.Token = localStorage.getItem("token")                 this.domain = localStorage.getItem("domain")             }         },     });     setInterval("app.GetDomain()", 3000); </script&gt; </html&gt;
 
我修改了index.html前端界面展示，在前端做了筛选，勉强满足需求了。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lanyi1998** [comment]
已经增加，见最新版
